name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.0 3.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Test against rails main
        if: ${{ matrix.ruby == 3.3 }}
        run: |
          bundle exec appraisal rails-main bundle install
          bundle exec appraisal rails-main rake test
      - name: Test against rails 6.0
        run: |
          bundle exec appraisal rails-7 bundle install
          bundle exec appraisal rails-7 rake test
      - name: Test against rails 5.2
        run: |
          bundle exec appraisal rails-6 bundle install
          bundle exec appraisal rails-6 rake test