name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.3]
        rails: ['rails-7', 'rails-main']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Appraisal
        run: gem install appraisal
  
      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3
          appraisal install

      - name: Test against Rails versions
        run: |
          bundle exec appraisal ${{ matrix.rails }} rake test