name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3]
        rails: ['rails-6', 'rails-7']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3
          gem install appraisal
          appraisal install

      - name: Test against rails main
        run: |
          bundle exec appraisal ${{ matrix.rails }} bundle install
          bundle exec appraisal ${{ matrix.rails }} rake test

