name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.3]
        rails: ['rails-6', 'rails-7']
    name: Ruby ${{ matrix.ruby }} with ${{ matrix.rails }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # Automatically installs gems and caches them
    - name: Install dependencies
      run: |
        gem install appraisal
        appraisal install
    - name: Run tests
      run: appraisal ${{ matrix.rails }} rake test
